"""
Single-experiment runner for the Synthetic HR-MDP benchmark.

For one (p_switch, seed) combination:
  1. Fit a Gaussian HMM on synthetic returns generated by the env.
  2. Train baseline / hard / soft A2C agents on the training env.
  3. Evaluate ALL four policies (3 RL variants + Oracle) on the SAME test
     trajectory — same env seed → same regime sequence → same realised
     returns.  Differences between agents come purely from action choices.
  4. Compute step-wise regret = log_wealth_oracle − log_wealth_agent.
  5. Save curves, training histories, and a per-seed figure.

Stand-alone invocation runs one experiment; `sweep.py` loops this across
multiple p_switch values × seeds to build Figure 1.
"""

import os
import json
import argparse
import numpy as np
import torch
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from synthetic_env import (
    SyntheticHRMDPEnv, Oracle, fit_hmm_on_synthetic,
    N_ASSETS, N_REGIMES, REGIME_NAMES,
)
from train import train_a2c


# -----------------------------------------------------------------------------
# Device
# -----------------------------------------------------------------------------

DEVICE = (
    "cuda" if torch.cuda.is_available() else
    "mps"  if torch.backends.mps.is_available() else
    "cpu"
)


# -----------------------------------------------------------------------------
# Greedy rollout
# -----------------------------------------------------------------------------

def greedy_rollout(env, eval_seed: int, *,
                    actor=None, oracle=None, device: str = "cpu"):
    """
    Step the env to termination using a deterministic policy.

      actor  : trained PyTorch module (uses mean of Gaussian as action)
      oracle : Oracle instance      (uses true regime label)

    Returns
    -------
    log_wealth : (T+1,) array of log(portfolio_value)
    cum_reward : float (sum of step rewards)
    weights_history : (T, N) array of weights actually played each step
    """
    state, _ = env.reset(seed=eval_seed)
    done       = False
    log_wealth = [0.0]            # log(1.0) at step 0
    cum_reward = 0.0
    weights_history = []

    if actor is not None:
        actor.eval()

    with torch.no_grad():
        while not done:
            if oracle is not None:
                true_regime = env.regime_history[-1]
                weights = oracle.get_weights(true_regime)
            else:
                s_t      = torch.tensor(state, dtype=torch.float32).unsqueeze(0).to(device)
                mean, _  = actor(s_t)
                weights  = mean.cpu().numpy()[0]

            weights_history.append(np.asarray(weights, dtype=np.float32))
            state, reward, done, _, _ = env.step(weights)
            cum_reward += reward
            log_wealth.append(float(np.log(max(env.portfolio_value, 1e-12))))

    return np.asarray(log_wealth), cum_reward, np.asarray(weights_history)


# -----------------------------------------------------------------------------
# Single experiment
# -----------------------------------------------------------------------------

def run_single_experiment(p_switch: float = 0.05,
                          seed: int = 0,
                          epochs: int = 200,
                          train_episode_len: int = 500,
                          eval_episode_len: int = 2000,
                          hmm_train_steps: int = 5000,
                          device: str = DEVICE,
                          verbose: bool = False) -> dict:
    """
    Returns a dict with:
      'p_switch', 'seed'                       — bookkeeping
      'log_wealth'    : {variant: list[float]} — one curve per agent
      'regrets'       : {variant: list[float]} — oracle minus agent (RL only)
      'final_regret'  : {variant: float}       — last value of regret curve
      'cum_reward'    : {variant: float}       — sum of step rewards
      'final_log_wealth' : {variant: float}
      'histories'     : {variant: list[float]} — training reward per epoch
      'true_regime_seq': list[int]             — for diagnostic plots
    """
    # ── 1. HMM fit (deterministic per p_switch — independent of RL seed) ──
    hmm    = fit_hmm_on_synthetic(p_switch, n_steps=hmm_train_steps, seed=42)
    oracle = Oracle()

    # ── 2. Set RL seed (controls actor init + training stochasticity) ─────
    torch.manual_seed(seed)
    np.random.seed(seed)

    histories = {}
    actors    = {}
    for variant in ("baseline", "hard", "soft"):
        train_env = SyntheticHRMDPEnv(
            p_switch=p_switch,
            episode_len=train_episode_len,
            variant=variant,
            hmm=hmm,
            seed=seed * 100 + hash(variant) % 97,
        )
        if verbose:
            print(f"  Training [{variant}]   p_switch={p_switch}   seed={seed}")
        actor, _, hist = train_a2c(
            train_env, variant, device,
            epochs=epochs, verbose=verbose,
        )
        actors[variant]    = actor
        histories[variant] = hist

    # ── 3. Evaluate on a SHARED trajectory (same seed → same regime/return)
    eval_seed = seed * 10_000 + 7
    log_wealth      = {}
    cum_rewards     = {}
    weights_played  = {}
    true_regime_seq = None

    for variant in ("baseline", "hard", "soft"):
        env = SyntheticHRMDPEnv(
            p_switch=p_switch, episode_len=eval_episode_len,
            variant=variant, hmm=hmm, seed=eval_seed,
        )
        lw, cr, ws = greedy_rollout(env, eval_seed,
                                     actor=actors[variant], device=device)
        log_wealth[variant]     = lw
        cum_rewards[variant]    = cr
        weights_played[variant] = ws

    # Oracle (uses true regime; same eval_seed → identical trajectory)
    env_oracle = SyntheticHRMDPEnv(
        p_switch=p_switch, episode_len=eval_episode_len,
        variant="oracle", hmm=hmm, seed=eval_seed,
    )
    lw_o, cr_o, ws_o = greedy_rollout(env_oracle, eval_seed,
                                       oracle=oracle, device=device)
    log_wealth["oracle"]     = lw_o
    cum_rewards["oracle"]    = cr_o
    weights_played["oracle"] = ws_o
    true_regime_seq          = list(env_oracle.regime_history)   # length window+T

    # ── 4. Regret curves (positive ⇒ agent below oracle) ──────────────────
    regrets = {v: log_wealth["oracle"] - log_wealth[v]
               for v in ("baseline", "hard", "soft")}

    final_regret     = {v: float(regrets[v][-1])    for v in regrets}
    final_log_wealth = {v: float(log_wealth[v][-1]) for v in log_wealth}

    return {
        "p_switch":         p_switch,
        "seed":             seed,
        "log_wealth":       {k: v.tolist() for k, v in log_wealth.items()},
        "regrets":          {k: v.tolist() for k, v in regrets.items()},
        "final_regret":     final_regret,
        "final_log_wealth": final_log_wealth,
        "cum_reward":       cum_rewards,
        "histories":        histories,
        "true_regime_seq":  true_regime_seq,
    }


# -----------------------------------------------------------------------------
# Per-experiment plots
# -----------------------------------------------------------------------------

def plot_single_experiment(result: dict, save_dir: str):
    os.makedirs(save_dir, exist_ok=True)
    p_switch = result["p_switch"]
    seed     = result["seed"]
    suffix   = f"p{p_switch:.3f}_seed{seed}"

    colors = {
        "oracle":   "black",
        "soft":     "green",
        "hard":     "darkorange",
        "baseline": "steelblue",
    }
    labels = {
        "oracle":   "Oracle (perfect regime knowledge)",
        "soft":     "Soft MoE",
        "hard":     "Hard Routing",
        "baseline": "Baseline A2C",
    }

    # ── Wealth curves ────────────────────────────────────────────────────
    fig, ax = plt.subplots(figsize=(11, 5))
    for variant in ("oracle", "soft", "hard", "baseline"):
        lw = np.asarray(result["log_wealth"][variant])
        ax.plot(np.exp(lw) - 1, color=colors[variant], lw=1.6, label=labels[variant])
    ax.set_xlabel("Step"); ax.set_ylabel("Cumulative return")
    ax.set_title(f"Synthetic HR-MDP — Cumulative Return  (p_switch={p_switch}, seed={seed})")
    ax.axhline(0, color="grey", lw=0.7, ls="--")
    ax.grid(alpha=0.3); ax.legend(fontsize=9, loc="upper left")
    plt.tight_layout()
    plt.savefig(os.path.join(save_dir, f"wealth_{suffix}.png"), dpi=150, bbox_inches="tight")
    plt.close()

    # ── Regret curves ─────────────────────────────────────────────────────
    fig, ax = plt.subplots(figsize=(11, 5))
    for variant in ("baseline", "hard", "soft"):
        reg = np.asarray(result["regrets"][variant])
        ax.plot(reg, color=colors[variant], lw=1.6, label=labels[variant])
    ax.axhline(0, color="black", lw=0.8, ls=":", label="Oracle (regret=0)")
    ax.set_xlabel("Step"); ax.set_ylabel("Regret  (log-wealth: oracle − agent)")
    ax.set_title(f"Synthetic HR-MDP — Regret vs Oracle  (p_switch={p_switch}, seed={seed})")
    ax.grid(alpha=0.3); ax.legend(fontsize=9, loc="upper left")
    plt.tight_layout()
    plt.savefig(os.path.join(save_dir, f"regret_{suffix}.png"), dpi=150, bbox_inches="tight")
    plt.close()

    # ── Training curves ──────────────────────────────────────────────────
    fig, ax = plt.subplots(figsize=(11, 5))
    for variant in ("baseline", "hard", "soft"):
        h = result["histories"][variant]
        ax.plot(h, alpha=0.3, color=colors[variant])
        import pandas as pd
        ma = pd.Series(h).rolling(20).mean()
        ax.plot(ma, lw=2, color=colors[variant], label=f"{labels[variant]} (20-ep MA)")
    ax.set_xlabel("Epoch"); ax.set_ylabel("Episode reward")
    ax.set_title(f"A2C Training — Synthetic HR-MDP  (p_switch={p_switch}, seed={seed})")
    ax.grid(alpha=0.3); ax.legend(fontsize=9)
    plt.tight_layout()
    plt.savefig(os.path.join(save_dir, f"training_{suffix}.png"), dpi=150, bbox_inches="tight")
    plt.close()


# -----------------------------------------------------------------------------
# CLI
# -----------------------------------------------------------------------------

def _save_result(result: dict, path: str):
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    # histories are lists of floats (Python ints/floats), already serialisable
    with open(path, "w") as f:
        json.dump(result, f, indent=2)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--p_switch", type=float, default=0.05)
    parser.add_argument("--seed",     type=int,   default=0)
    parser.add_argument("--epochs",   type=int,   default=200)
    parser.add_argument("--train_len", type=int,  default=500)
    parser.add_argument("--eval_len",  type=int,  default=2000)
    parser.add_argument("--out_dir",   type=str,  default="results")
    parser.add_argument("--verbose",   action="store_true")
    args = parser.parse_args()

    print(f"[Synthetic HR-MDP] device={DEVICE}  "
          f"p_switch={args.p_switch}  seed={args.seed}  epochs={args.epochs}")

    result = run_single_experiment(
        p_switch=args.p_switch, seed=args.seed,
        epochs=args.epochs,
        train_episode_len=args.train_len,
        eval_episode_len=args.eval_len,
        verbose=args.verbose,
    )

    suffix      = f"p{args.p_switch:.3f}_seed{args.seed}"
    json_path   = os.path.join(args.out_dir, f"experiment_{suffix}.json")
    _save_result(result, json_path)
    plot_single_experiment(result, args.out_dir)

    print("\n" + "=" * 60)
    print(f"  Final log-wealth   (higher = better)")
    print("=" * 60)
    for v in ("oracle", "soft", "hard", "baseline"):
        print(f"  {v:<10s}: {result['final_log_wealth'][v]:+.4f}")
    print("\n" + "=" * 60)
    print(f"  Final regret vs oracle  (lower = better)")
    print("=" * 60)
    for v in ("baseline", "hard", "soft"):
        print(f"  {v:<10s}: {result['final_regret'][v]:+.4f}")
    print("=" * 60)
    print(f"\nSaved → {json_path}")
