#!/bin/bash
#PBS -N URC_RL_dsr
#PBS -P spms_cspun
#PBS -q gpu_a40
#PBS -M BHARATH007@ntu.edu.sg
#PBS -m abe
#PBS -l walltime=48:00:00
#PBS -l select=1:ncpus=4:ngpus=1:mem=32gb
#PBS -o URC_RL_dsr.out
#PBS -e URC_RL_dsr.err

module load anaconda2025/2025-gpu
eval "$(/usr/local/anaconda2025/bin/conda shell.bash hook)"
source /home/bharath007/Regime-Aware-RL-URECA-/venv/bin/activate

cd /home/bharath007/Regime-Aware-RL-URECA-/Final

python -u run.py --variant both --seeds 3 --reward_mode dsr
